# Generated by Django 4.0.5 on 2022-06-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Descriptions', models.TextField(blank=True)),
                ('Start_date', models.DateField(auto_now_add=True)),
                ('Estemated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Descriptions', models.TextField(blank=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Recurring', models.BooleanField(default=False)),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='Wallet.source')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Descriptions', models.TextField(blank=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Recurring', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Wallet.category')),
            ],
        ),
    ]
