# Generated by Django 4.0.5 on 2022-06-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Category', models.CharField(choices=[('FOOD', 'FOOD'), ('COFFEE', 'COFFEE'), ('RENT', 'RENT'), ('BILLS', 'BILLS'), ('GROCERY', 'GROCERY'), ('OTHERS', 'OTHERS')], max_length=100)),
                ('Description', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Source', models.CharField(choices=[('SALARY', 'SALARY'), ('BUSINESS', 'BUSINESS'), ('SAVING', 'SAVING'), ('BONUS', 'BONUS'), ('OTHERS', 'OTHERS')], max_length=100)),
                ('Description', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Description', models.TextField(blank=True)),
                ('Start_date', models.DateField(auto_now_add=True)),
                ('Estemated_date', models.DateField()),
            ],
        ),
    ]
