# Generated by Django 4.0.5 on 2022-06-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='Recurring',
            new_name='recurring',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='Recurring',
            new_name='recurring',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='Source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Estemated_date',
            new_name='estemated_date',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Start_date',
            new_name='start_date',
        ),
    ]
