# Generated by Django 4.0.5 on 2022-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0002_alter_expense_category_alter_income_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Category',
            field=models.CharField(choices=[('FOOD', 'FOOD'), ('COFFEE', 'COFFEE'), ('RENT', 'RENT'), ('BILLS', 'BILLS'), ('GROCERY', 'GROCERY'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='Source',
            field=models.CharField(choices=[('SALARY', 'SALARY'), ('BUSINESS', 'BUSINESS'), ('SAVING', 'SAVING'), ('BONUS', 'BONUS'), ('OTHERS', 'OTHERS')], max_length=100),
        ),
    ]
