# Generated by Django 4.0.5 on 2022-06-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0003_alter_expense_category_alter_income_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='Descriptions',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='Descriptions',
            new_name='Description',
        ),
    ]
